deal:
    path:     /
    defaults: { _controller: "BackendBundle:Deal:index" }
    methods:  GET

deal_find:
    path:     /find
    defaults: { _controller: "BackendBundle:Deal:find" }
    methods:  [POST, GET]

deal_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Deal:show" }
    methods:  GET

deal_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Deal:new" }
    methods:  [GET, POST]

deal_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Deal:edit" }
    methods:  [GET, POST, PUT]

deal_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Deal:delete" }
    methods:  [POST, DELETE]
    
deal_batch:
    path:     /deal_batch
    defaults: { _controller: "BackendBundle:Deal:batch" }
    methods:  POST
