openingcategory:
    path:     /
    defaults: { _controller: "BackendBundle:OpeningCategory:index" }
    methods:  GET

openingcategory_find:
    path:     /find
    defaults: { _controller: "BackendBundle:OpeningCategory:find" }
    methods:  [POST, GET]

openingcategory_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:OpeningCategory:show" }
    methods:  GET

openingcategory_new:
    path:     /new
    defaults: { _controller: "BackendBundle:OpeningCategory:new" }
    methods:  [GET, POST]

openingcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:OpeningCategory:edit" }
    methods:  [GET, POST, PUT]

openingcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:OpeningCategory:delete" }
    methods:  [POST, DELETE]
    
openingcategory_batch:
    path:     /openingcategory_batch
    defaults: { _controller: "BackendBundle:OpeningCategory:batch" }
    methods:  POST
