post_image:
    path:     /
    defaults: { _controller: "BackendBundle:PostImage:index" }
    methods:  GET

post_image_find:
    path:     /find
    defaults: { _controller: "BackendBundle:PostImage:find" }
    methods:  [POST, GET]

post_image_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:PostImage:show" }
    methods:  GET

post_image_new:
    path:     /new
    defaults: { _controller: "BackendBundle:PostImage:new" }
    methods:  [GET, POST]

post_image_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:PostImage:edit" }
    methods:  [GET, POST, PUT]

post_image_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:PostImage:delete" }
    methods:  [POST, DELETE]
    
post_image_batch:
    path:     /post_image_batch
    defaults: { _controller: "BackendBundle:PostImage:batch" }
    methods:  POST
