postimage:
    path:     /
    defaults: { _controller: "BackendBundle:PostImage:index" }
    methods:  GET

postimage_find:
    path:     /find
    defaults: { _controller: "BackendBundle:PostImage:find" }
    methods:  [POST, GET]

postimage_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:PostImage:show" }
    methods:  GET

postimage_new:
    path:     /new
    defaults: { _controller: "BackendBundle:PostImage:new" }
    methods:  [GET, POST]

postimage_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:PostImage:edit" }
    methods:  [GET, POST, PUT]

postimage_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:PostImage:delete" }
    methods:  [POST, DELETE]
    
postimage_batch:
    path:     /post_image_batch
    defaults: { _controller: "BackendBundle:PostImage:batch" }
    methods:  POST
