post:
    path:     /
    defaults: { _controller: "BackendBundle:Post:index" }
    methods:  GET

post_find:
    path:     /find
    defaults: { _controller: "BackendBundle:Post:find" }
    methods:  [POST, GET]

post_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Post:show" }
    methods:  GET

post_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Post:new" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Post:edit" }
    methods:  [GET, POST, PUT]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Post:delete" }
    methods:  [POST, DELETE]
    
post_batch:
    path:     /post_batch
    defaults: { _controller: "BackendBundle:Post:batch" }
    methods:  POST

post_upload_image:
    path:     /uploadimage
    defaults: { _controller: "BackendBundle:Post:uploadImage" }
    methods:  POST

post_delete_image:
    path:     /{id}/deleteimage
    defaults: { _controller: "BackendBundle:Post:deleteImage" }
    methods:  GET
