imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BackendBundle/Resources/config/services.yml" }
    - { resource: "@FrontendBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        careers_apply:         %careers.apply.online%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    host:      %mailer_host%
    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%
    auth_mode: %mailer_auth_mode%
    transport: %mailer_transport%
    encryption: %mailer_encryption%
#    spool:
#        type: file
#        path: %kernel.root_dir%/spool
    disable_delivery: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: BackendBundle\Entity\SystemUser
    registration:
        form:
            type:               BackendBundle\Form\registrationType
            name:               backendbundle_user_registration
        confirmation:
            enabled:    false
    profile:
        form:
            type:               BackendBundle\Form\ProfileFormType
            name:               backendbundle_user_profile
    from_email:
        address:        fuzenetcuba@fuzenetcuba.com
        sender_name:    FuzenetCuba
    service:
        mailer:                 fos_user.mailer.twig_swift
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default
    resetting:
        token_ttl: 40264
        form:
            type:               fos_user_resetting
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        business_image:
            uri_prefix:         /images/business
            upload_destination: %kernel.root_dir%/../web/images/business
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              app.vichuploader.namer #vich_uploader.namer_uniqid
        business_gallery_image:
            uri_prefix:         /images/business/gallery
            upload_destination: %kernel.root_dir%/../web/images/business/gallery
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              app.vichuploader.namer #vich_uploader.namer_uniqid
        deal_image:
            uri_prefix:         /images/deals
            upload_destination: %kernel.root_dir%/../web/images/deals
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              app.vichuploader.namer #vich_uploader.namer_uniqid
        user_image:
            uri_prefix:         /images/users
            upload_destination: %kernel.root_dir%/../web/images/users
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              app.vichuploader.namer #vich_uploader.namer_uniqid
        setting_image:
            uri_prefix:         /images/settings
            upload_destination: %kernel.root_dir%/../web/images/settings
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              app.vichuploader.namer #vich_uploader.namer_uniqid

#config for HWIOAuthBundle
hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)and

    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: backend

    connect:
        account_connector: app.provider.oauth
        confirmation: true

    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebookId
            google: googleId

    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_client_id%
            client_secret:       %facebook_client_secret%
            scope:               "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email:           email
                profilepicture:  picture.data.url
            options:
                display:         popup

        google:
            type:                google
            client_id:           %google_client_id%
            client_secret:       %google_client_secret%
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email:           email

    http_client:
        verify_peer:   true
        ignore_errors: true
        max_redirects: 5
       # timeout:       %client.timeout%

stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:
            tree: true
            timestampable: true
            sluggable: true
            translatable: true

jms_i18n_routing:
    default_locale: en
    locales: [en, es]
    strategy: prefix_except_default