# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

        in_memory:
            memory: ~

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_BUSSINES:      ROLE_USER
        ROLE_ADMIN:         ROLE_BUSSINES


    firewalls:
        backend:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:             fos_user_security_login
                check_path:             fos_user_security_check
                always_use_default_target_path: false
                default_target_path:            /admin
                use_referer: true
            logout:
                target: /login
            anonymous:    true

            # config for HWIOAuthBundle
            oauth:
                failure_path: /login
                login_path: fos_user_security_login
                check_path: /connect_check
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                oauth_user_provider:
                  service: hwi_oauth.user.provider.fosub_bridge
                  #service: app.provider.oauth

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html



        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
        # --------------------- ANONYMOUS ACTIONS ---------------------
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # --------------------- PROFILE SECURITY ACTIONS ---------------------
        - { path: ^/admin/change/profile, role: IS_AUTHENTICATED_FULLY }

        # --------------------- ADMIN ACTIONS ---------------------
        - { path: ^/admin/, role: ROLE_ADMIN }

        # --------------------- AUTENTICATED USER ACTIONS ---------------------
        - { path: ^/frontend_loged$, role: IS_AUTHENTICATED_FULLY }