# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

        in_memory:
            memory: ~

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CUSTOMER:      ROLE_USER
        ROLE_BUSINESS:      ROLE_CUSTOMER
        ROLE_SUPERVISOR:    ROLE_BUSINESS
        ROLE_ADMIN:         ROLE_BUSINESS, ROLE_SUPERVISOR


    firewalls:
        backend:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:             fos_user_security_login
                check_path:             fos_user_security_check
                always_use_default_target_path: true
                default_target_path:            /
                use_referer: true
            logout:       true
            anonymous:    true

            # config for HWIOAuthBundle
            oauth:
                failure_path: /login
                login_path: fos_user_security_login
                check_path: /connect_check
                provider: fos_userbundle
                remember_me: true
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                oauth_user_provider:
                  #service: hwi_oauth.user.provider.fosub_bridge
                  service: app.provider.oauth

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html



        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
        # --------------------- ANONYMOUS ACTIONS ---------------------
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # --------------------- PROFILE SECURITY ACTIONS ---------------------
        - { path: ^/admin/change/profile, role: IS_AUTHENTICATED_FULLY }

        # --------------------- SUPERVISOR ACTIONS [ONLY VIEW AND DOWNLOAD INFO] ---------------------
        - { path: ^/admin/$, role: ROLE_SUPERVISOR }

        - { path: ^/admin/alert/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/alert/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/alert/.+/show, role: ROLE_SUPERVISOR }
        - { path: ^/admin/alert/.+/details, role: ROLE_SUPERVISOR }
        - { path: ^/admin/alert/unchecked_alerts, role: ROLE_SUPERVISOR }
        - { path: ^/admin/alert/count_unchecked_alerts, role: ROLE_SUPERVISOR }

        - { path: ^/admin/candidate/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/candidate/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/candidate/.+/show, role: ROLE_SUPERVISOR }
        - { path: ^/admin/candidate/.+/pdf_report, role: ROLE_SUPERVISOR }

        - { path: ^/admin/settings/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/settings/.+/show, role: ROLE_SUPERVISOR }
        - { path: ^/admin/settings/setting/.+, role: ROLE_SUPERVISOR }

#        - { path: ^/admin/mails/send, role: ROLE_SUPERVISOR }

        - { path: ^/admin/subscription/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/subscription/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/subscription/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/customer/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/customer/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/customer/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/reward/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/reward/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/reward/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/deal/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/deal/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/deal/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/category/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/category/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/category/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/opening_category/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/opening_category/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/opening_category/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/business/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/business/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/business/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/user/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/user/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/user/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/opening/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/opening/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/opening/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/feedback/$, role: ROLE_SUPERVISOR }
        - { path: ^/admin/feedback/find, role: ROLE_SUPERVISOR }
        - { path: ^/admin/feedback/.+/show, role: ROLE_SUPERVISOR }

        - { path: ^/admin/logout-ajax, role: ROLE_SUPERVISOR }

        # --------------------- ADMIN ACTIONS ---------------------
        - { path: ^/admin/, role: ROLE_ADMIN }

        # --------------------- AUTENTICATED USER ACTIONS ---------------------
        - { path: ^/frontend_loged$, role: IS_AUTHENTICATED_FULLY }