<?php

namespace BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PressPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressPostRepository extends EntityRepository
{
}
