frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

frontend_static_page:
    path:     /base/{name}
    defaults: { _controller: FrontendBundle:Default:staticPage }

frontend_loged_in:
    path:     /frontend_loged
    defaults: { _controller: FrontendBundle:Default:logedIn }

deals:
    path:     /deals
    defaults: { _controller: FrontendBundle:Deal:index }
    options:
        expose: true

deal_details:
    path:     /deal/{slug}
    defaults: { _controller: FrontendBundle:Deal:details }

business_list:
    path:     /businesses
    defaults: { _controller: FrontendBundle:Business:index }
    options:
        expose: true

business_details:
    path:     /business/{slug}
    defaults: { _controller: FrontendBundle:Business:details }

membership:
    path:     /membership
    defaults: { _controller: FrontendBundle:User:index }

subscription_request:
    path:     /subscribe/request
    defaults: { _controller: FrontendBundle:Subscription:subscribe }

subscription_confirm:
    path:     /subscribe/confirm/{id}
    defaults: { _controller: FrontendBundle:Subscription:confirm }
    methods:  GET

mall_map:
    path:     /mall-map/{hl}
    defaults: { _controller: FrontendBundle:Default:map, hl:~ }

careers_index:
    path:     /careers
    defaults: { _controller: FrontendBundle:Careers:index }

careers_find:
    path:     /careers/find
    defaults: { _controller: FrontendBundle:Careers:find }

careers_apply:
    path:     /careers/{slug}/apply
    defaults: { _controller: FrontendBundle:Careers:apply }

careers_store:
    path:     /careers/store
    defaults: { _controller: FrontendBundle:Careers:store }
    options:
        expose: true