frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

frontend_loged_in:
    path:     /frontend_loged
    defaults: { _controller: FrontendBundle:Default:logedIn }

deals:
    path:     /deals
    defaults: { _controller: FrontendBundle:Deal:index }

deal_details:
    path:     /deal/{slug}
    defaults: { _controller: FrontendBundle:Deal:details }