services:
    kernel.request.remove.deal.filter:
        class: FrontendBundle\Listener\RequestListener
        arguments: [@session, 'deals', 'deal_filter']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request' }

    kernel.request.remove.business.filter:
        class: FrontendBundle\Listener\RequestListener
        arguments: [@session, 'businesses', 'business_filter']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request' }
