backend_press:
    resource: "@BackendBundle/Resources/config/routing/presspost.yml"
    prefix:   /press

backend_postimage:
    resource: "@BackendBundle/Resources/config/routing/postimage.yml"
    prefix:   /postimage

backend_post:
    resource: "@BackendBundle/Resources/config/routing/post.yml"
    prefix:   /post

backend_alert:
    resource: "@BackendBundle/Resources/config/routing/alert.yml"
    prefix:   /alert

backend_candidate:
    resource: "@BackendBundle/Resources/config/routing/candidate.yml"
    prefix:   /candidate

backend_settings:
    resource: "@BackendBundle/Resources/config/routing/settings.yml"
    prefix:   /settings

backend_mails:
    resource: "@BackendBundle/Resources/config/routing/mails.yml"
    prefix:   /mails

backend_subscription:
    resource: "@BackendBundle/Resources/config/routing/subscription.yml"
    prefix:   /subscription

backend_customer:
    resource: "@BackendBundle/Resources/config/routing/customer.yml"
    prefix:   /customer

backend_reward:
    resource: "@BackendBundle/Resources/config/routing/reward.yml"
    prefix:   /reward

backend_deal:
    resource: "@BackendBundle/Resources/config/routing/deal.yml"
    prefix:   /deal

backend_category:
    resource: "@BackendBundle/Resources/config/routing/category.yml"
    prefix:   /category

backend_opening_category:
    resource: "@BackendBundle/Resources/config/routing/opening_category.yml"
    prefix:   /opening_category

backend_business:
    resource: "@BackendBundle/Resources/config/routing/business.yml"
    prefix:   /business

backend_helpers:
    resource: "@BackendBundle/Resources/config/routing/helpers.yml"
    prefix:   /helpers
    
backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }

config_routing_user:
    resource: "@BackendBundle/Resources/config/routing/user.yml"
    prefix:   /user

backend_opening:
    resource: "@BackendBundle/Resources/config/routing/opening.yml"
    prefix:   /opening

fos_user_logout_ajax:
    path: /logout-ajax
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_security_logout
        permanent: true
    options:
        expose: true

backend_feedback:
    resource: "@BackendBundle/Resources/config/routing/feedback.yml"
    prefix:   /feedback

backend_static_page:
    path:     /base/{name}
    defaults: { _controller: BackendBundle:Default:staticPage }