services:
    alert.manager:
        class: BackendBundle\Model\AlertManager
        arguments: ["@doctrine.orm.entity_manager"]

    business.manager:
        class: BackendBundle\Model\BusinessManager
        arguments: ["@doctrine.orm.entity_manager"]

    category.manager:
        class: BackendBundle\Model\CategoryManager
        arguments: ["@doctrine.orm.entity_manager"]

    opening.category.manager:
        class: BackendBundle\Model\OpeningCategoryManager
        arguments: ["@doctrine.orm.entity_manager"]

    deal.manager:
        class: BackendBundle\Model\DealManager
        arguments: ["@doctrine.orm.entity_manager"]

    reward.manager:
        class: BackendBundle\Model\RewardManager
        arguments: ["@doctrine.orm.entity_manager"]

    customer.manager:
        class: BackendBundle\Model\CustomerManager
        arguments: ["@doctrine.orm.entity_manager", "@mailer"]

    subscription.manager:
        class: BackendBundle\Model\SubscriptionManager
        arguments: ["@doctrine.orm.entity_manager"]

    feedback.manager:
        class: BackendBundle\Model\FeedbackManager
        arguments: ["@doctrine.orm.entity_manager"]

    candidate.manager:
        class: BackendBundle\Model\CandidateManager
        arguments: ["@doctrine.orm.entity_manager"]

    opening.manager:
        class: BackendBundle\Model\OpeningManager
        arguments: ["@doctrine.orm.entity_manager", "@mailer", "@filesystem", "@spraed.pdf.generator", "%careers.pdf.store%", "%careers.pdf.store.report%", "%careers.contact.email%"]
        
    backendbundle_user.registration.form.type:
        class: BackendBundle\Form\registrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: backendbundle_user_registration }

    backendbundle_user.profile.form.type:
        class: BackendBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: backendbundle_user_profile }

    kernel.listener.logged_in_user_listener:
        class: BackendBundle\Listener\InteractiveLoginListener
        arguments: [ "@router", "@security.authorization_checker" ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    tccsecuritybundle_user.listener.registration:
        class: BackendBundle\Listener\RegistrationListener
        tags:
            - { name: kernel.event_subscriber }

    app.vichuploader.namer:
        class: BackendBundle\Namer\VichUploaderNamer
        tags:
            - { name: namer }

    app.twig.json_decode_extension:
        class: BackendBundle\Twig\JsonDecodeExtension
        tags:
            - { name: twig.extension }

    app.twig.unformat_phone_extension:
        class: BackendBundle\Twig\UnformatPhoneExtension
        tags:
            - { name: twig.extension }